In [ ]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Master/Language Generation and Summarization/Project/caption_regression.csv')

In [ ]:
df

caption   u_id  adjectives   \
0    "A blue boat themed bathroom with a life prese...     1         1.00   
1    "This is a blue and white bathroom with a wall...     2         3.00   
2    "A blue boat themed bathroom with a life prese...     1         2.00   
3    "A blue boat themed bathroom with a life prese...     1         2.00   
4    "A blue boat themed bathroom with a life prese...     1         2.00   
..                                                 ...   ...          ...   
133  "One yellow and black motorcycleparked next to...    91         1.55   
134  "A yellow motorcycle is parked next to ablue m...    92         1.55   
135  "A man with his dog on a leash talking toanoth...    93         1.55   
136   "A bath room with a toilet a bath tub anda sink"    94         1.55   
137  "A bathroom with a white toilet next to awhite...    95         1.55   

     figurative_language   diverse_vocab  label   
0                    3.00           1.00       1  
1                    2.00           1.00       1  
2                    1.00           3.00       1  
3                    1.00           1.00       1  
4                    3.00           1.00       1  
..                    ...            ...     ...  
133                  2.15           1.97       0  
134                  2.15           1.97       0  
135                  2.15           1.97       0  
136                  2.15           1.97       0  
137                  2.15           1.97       0  

[138 rows x 6 columns]

In [ ]:
y = df['label ']
x = df[['caption ','adjectives ','figurative_language ','diverse_vocab']]

In [ ]:
linear_regression = LinearRegression()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
def vectorize(x):
  x_array = [x]
  vectorizer.fit(x_array)
  return vectorizer.transform(x_array).toarray()

df['caption1 '] = df['caption '].apply(vectorize)

In [ ]:
df.fillna(0)

caption   u_id  adjectives   \
0    "A blue boat themed bathroom with a life prese...     1         1.00   
1    "This is a blue and white bathroom with a wall...     2         3.00   
2    "A blue boat themed bathroom with a life prese...     1         2.00   
3    "A blue boat themed bathroom with a life prese...     1         2.00   
4    "A blue boat themed bathroom with a life prese...     1         2.00   
..                                                 ...   ...          ...   
133  "One yellow and black motorcycleparked next to...    91         1.55   
134  "A yellow motorcycle is parked next to ablue m...    92         1.55   
135  "A man with his dog on a leash talking toanoth...    93         1.55   
136   "A bath room with a toilet a bath tub anda sink"    94         1.55   
137  "A bathroom with a white toilet next to awhite...    95         1.55   

     figurative_language   diverse_vocab  label   \
0                    3.00           1.00       1   
1                    2.00           1.00       1   
2                    1.00           3.00       1   
3                    1.00           1.00       1   
4                    3.00           1.00       1   
..                    ...            ...     ...   
133                  2.15           1.97       0   
134                  2.15           1.97       0   
135                  2.15           1.97       0   
136                  2.15           1.97       0   
137                  2.15           1.97       0   

                                  caption1   
0          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
1    [[2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]]  
2          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
3          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
4          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
..                                      ...  
133              [[2, 2, 1, 1, 1, 2, 1, 1]]  
134                 [[1, 1, 2, 1, 1, 1, 1]]  
135              [[1, 1, 1, 2, 1, 1, 1, 1]]  
136                 [[1, 2, 1, 1, 1, 1, 1]]  
137              [[1, 1, 1, 1, 1, 1, 1, 1]]  

[138 rows x 7 columns]

In [ ]:
df['caption '] = df['caption1 ']
x = df[['adjectives ','figurative_language ','diverse_vocab']]

In [ ]:
x['adjectives '] = 1.0 / x['adjectives '].astype('float64') 
x['figurative_language '] = 1.0 / x['figurative_language '].astype('float64')
x['diverse_vocab'] = 1.0 / x['diverse_vocab'].astype('float64')

<ipython-input-70-36ac64ae5c34>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['adjectives '] = 1.0 / x['adjectives '].astype('float64')
<ipython-input-70-36ac64ae5c34>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['figurative_language '] = 1.0 / x['figurative_language '].astype('float64')
<ipython-input-70-36ac64ae5c34>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docum

In [ ]:
y = y.astype('float64')

In [ ]:
#x = StandardScaler().fit_transform(x).astype('float64').reshape(-1,1)
x = x.replace(np.nan, 0)
#np.argwhere(np.isnan(x))

In [ ]:
x

adjectives   figurative_language   diverse_vocab
0       1.000000              0.333333       1.000000
1       0.333333              0.500000       1.000000
2       0.500000              1.000000       0.333333
3       0.500000              1.000000       1.000000
4       0.500000              0.333333       1.000000
..           ...                   ...            ...
133     0.645161              0.465116       0.507614
134     0.645161              0.465116       0.507614
135     0.645161              0.465116       0.507614
136     0.645161              0.465116       0.507614
137     0.645161              0.465116       0.507614

[138 rows x 3 columns]

In [ ]:
classifier = linear_regression.fit(x,y)

In [ ]:
classifier.coef_

array([0.87710542, 0.74787666, 0.60671893])

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [ ]:
df = pd.read_csv('/content/caption_regression  - Sheet1 (1).csv')

In [ ]:
vectorizer = CountVectorizer(min_df=1)

def vectorize(x):
  x_array = [x]
  vectorizer.fit(x_array)
  return vectorizer.fit_transform(x_array).toarray()

df['caption1 '] = df['caption '].apply(vectorize)

In [ ]:
df

caption   adjectives   \
0    "A blue boat themed bathroom with a life prese...         1.00   
1    "This is a blue and white bathroom with a wall...         3.00   
2    "A blue boat themed bathroom with a life prese...         2.00   
3    "A blue boat themed bathroom with a life prese...         2.00   
4    "A blue boat themed bathroom with a life prese...         2.00   
..                                                 ...          ...   
133  "One yellow and black motorcycleparked next to...         1.55   
134  "A yellow motorcycle is parked next to ablue m...         1.55   
135  "A man with his dog on a leash talking toanoth...         1.55   
136   "A bath room with a toilet a bath tub anda sink"         1.55   
137  "A bathroom with a white toilet next to awhite...         1.55   

     figurative_language   diverse_vocab  label   \
0                    3.00           1.00       1   
1                    2.00           1.00       1   
2                    1.00           3.00       1   
3                    1.00           1.00       1   
4                    3.00           1.00       1   
..                    ...            ...     ...   
133                  2.15           1.97       0   
134                  2.15           1.97       0   
135                  2.15           1.97       0   
136                  2.15           1.97       0   
137                  2.15           1.97       0   

                                  caption1   
0          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
1    [[2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]]  
2          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
3          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
4          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]  
..                                      ...  
133              [[2, 2, 1, 1, 1, 2, 1, 1]]  
134                 [[1, 1, 2, 1, 1, 1, 1]]  
135              [[1, 1, 1, 2, 1, 1, 1, 1]]  
136                 [[1, 2, 1, 1, 1, 1, 1]]  
137              [[1, 1, 1, 1, 1, 1, 1, 1]]  

[138 rows x 6 columns]

In [ ]:
X = df[['caption1 ','adjectives ','figurative_language ','diverse_vocab']]
Y = df['label ']

In [ ]:
X

caption1   adjectives   \
0          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]         1.00   
1    [[2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]]         3.00   
2          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]         2.00   
3          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]         2.00   
4          [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]         2.00   
..                                      ...          ...   
133              [[2, 2, 1, 1, 1, 2, 1, 1]]         1.55   
134                 [[1, 1, 2, 1, 1, 1, 1]]         1.55   
135              [[1, 1, 1, 2, 1, 1, 1, 1]]         1.55   
136                 [[1, 2, 1, 1, 1, 1, 1]]         1.55   
137              [[1, 1, 1, 1, 1, 1, 1, 1]]         1.55   

     figurative_language   diverse_vocab  
0                    3.00           1.00  
1                    2.00           1.00  
2                    1.00           3.00  
3                    1.00           1.00  
4                    3.00           1.00  
..                    ...            ...  
133                  2.15           1.97  
134                  2.15           1.97  
135                  2.15           1.97  
136                  2.15           1.97  
137                  2.15           1.97  

[138 rows x 4 columns]

In [ ]:
clf = RandomForestClassifier()
clf.fit(vectorizer.fit_transform(df['caption ']).toarray(), Y)
#clf.predict(vectorizer.transform([‘apple is present’]).toarray())

RandomForestClassifier()

In [ ]:
clf.predict(vectorizer.transform(['apple is present today']).toarray())

array([1])

In [ ]:
vectorizer.fit_transform(df['caption ']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])